  name: test-and-connect-publish
  on:
    push:
      branches: [main]
    pull_request:
      branches: [main]
  
  jobs:
    test-and-connect-publish:
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v2

        - uses: r-lib/actions/setup-pandoc@v2

        - uses: r-lib/actions/setup-r@v2
          with:
            r-version: 4.3.1
            use-public-rspm: true

        - uses: r-lib/actions/setup-renv@v2
            
        - uses: r-lib/actions/check-r-package@v2

        - name: Create manifest.json
          shell: Rscript {0}
          run: |
            rsconnect::writeManifest()
            
        - name: Publish Connect content
          uses: rstudio/actions/connect-publish@main
          with:
            url: ${{ secrets.CONNECT_SERVER }}
            api-key: ${{ secrets.CONNECT_API_KEY }}
            access-type: logged_in
            dir: |
              .:/shiny-app-demo-cicd-github-actions